services:
  # Mario Blersch, 09.01.2026
  # -------------------------------------------------------
  # 1. GIS-Datenbank (PostgreSQL + PostGIS)
  # -------------------------------------------------------
  gis_db:
    image: postgis/postgis:17-3.5
    container_name: gis_db
    restart: always
    environment:
      POSTGRES_DB: gis_data
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: sicherheitspasswort123
    ports:
      - "5433:5432"
    volumes:
      - db_data_gis:/var/lib/postgresql/data
    networks:
      - gis-net

  # -------------------------------------------------------
  # 2. pgAdmin (Oberfläche für die GIS-Datenbank)
  # -------------------------------------------------------
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - gis_db
    networks:
      - gis-net

  # -------------------------------------------------------
  # 3. GeoServer (mit Verbindungsvariablen zu postgis db)
  # -------------------------------------------------------
  geoserver:
    image: kartoza/geoserver:2.28.0
    container_name: gis_geoserver
    restart: always
    environment:
# --- GeoServer Admin Login ---
      - GEOSERVER_ADMIN_PASSWORD=geoserver
      - GEOSERVER_ADMIN_USER=admin
      
      # --- Performance ---
      - INITIAL_MEMORY=2G
      - MAXIMUM_MEMORY=4G
      
      # --- Verbindung zur Datenbank (Anpassung für Kartoza Image) ---
      # Damit weiß GeoServer, dass er auf die DB warten soll
      - DB_BACKEND=POSTGRES
      - HOST=gis_db           # Name unseres DB-Containers (Service Name)
      - POSTGRES_PORT=5432
      - POSTGRES_DB=gis_data  # Name der DB, die wir im DB-Container definiert haben
      - POSTGRES_USER=admin   # User aus dem DB-Container
      - POSTGRES_PASS=sicherheitspasswort123 # Passwort aus dem DB-Container
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          memory: 1G
    ports:
      - "8080:8080"
    volumes:
      - geoserver_data:/opt/geoserver/data_dir
    depends_on:
      - gis_db
    networks:
      - gis-net

  # -------------------------------------------------------
  # 4. QGIS Server
  # -------------------------------------------------------
  qgis-server:
    image: camptocamp/qgis-server:3.34
    container_name: gis_qgis_server
    ports:
      - "8081:80"
    volumes:
      - ./qgis-projects:/etc/qgis
    environment:
      - QGIS_PROJECT_FILE=/etc/qgis/project.qgs
    networks:
      - gis-net

# -------------------------------------------------------
# Volumes & Networks
# -------------------------------------------------------
volumes:
  db_data_gis:        # PostGIS Daten dauerhaft speichern
  geoserver_data:     # GeoServer Konfigurationen speichern

networks:
  gis-net:
    driver: bridge